// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // La URL directa (sin pooler) es más segura para operaciones de schema
    // (db push) que la pooled, que a veces tiene problemas con DDL.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
